### PR TITLE
WIP: BlockHeader test

### PR DESCRIPTION
**Pull request by bobbyrauchenberg**
This is the first part of an attempt to help with the request for help with testing. I'm pretty new to Haskell, and also on holiday with very limited internet so thought i'd push this as a WIP. It all runs, and does a test of the BlockHeader json.

I'm not familiar with the convention for adding version numbers to the cabal file, so that's an obvious first problem I saw with my PR. Apologies, any guidance would be much appreciated!

I'll carry on with a version for Block

### CODE REVIEW

**Comment by tdietert** [comment]
I think you are getting a bit too explicit with the JSON tests. The JSON serialization tests do not need to check every field for equality, just that `Just x == Data.Aeson.encode $ Data.Aeson.decode x`. There shouldn't be so much code to test this, just the setup of the value `x`, and then this encode/decode round trip. 

Also, is there any way you can accomplish this without template haskell? I don't really want to use template haskell for things that are doable without. These tests can be done using quickcheck/hspec instead of hedgehog, if hedgehog is the reason you are using TH. If you can use hedgehog without it's TH features, that would be great.

**Comment by bobbyrauchenberg** [comment]
Thanks for the feedback, and apologies for some of my dodgy haskell - beyond exercises in books i'm pretty new to the language.

I was taking this explicity approach to the tests because I was under the impression (perhaps mistakenly) that the approach you suggest above would involved `FromJSON` instances for the various types.

There is a `FromJson` for Address so I did do the roundtrip approach in there.

From a look at the docs I think it's possible to run hedgehog without TH

**Comment by tdietert** [comment]
Ahh, true, I remember now-- you are right, there is no `FromJSON` instance because the only reason we needed JSON was to display the data in the browser window. For now, I think you can just remove the JSON tests, sorry for the work you've put in on them :/ Seems we don't need to/from JSON tests yet because there is no external software interacting w/ nanocoin. Once there is, there will need to be a more sophisticated RPC interface, which could use JSON, and only then would we need the JSON roundtrip tests.

**Comment by bobbyrauchenberg** [comment]
No problem, it was still a good learning exercise for me :) I've removed the TH stuff.

If you're happy for me to procede I can just remove the JSON tests, and use the generators I've got (where appropriate) to test the serialization (using the roundtrip approach)

**Comment by bobbyrauchenberg** [comment]
I've removed the JSON tests, and added test for the manual serialization instances

**Comment by tdietert** [comment]
Can you condense the serialization tests into a single file `test/Serialization.hs` or so? and as for the `genX` functions, can you move them from `Nanocoin.Utils` into `test/Gen.hs`? I don't imagine we will need these randomly generated values in the main library.

**Comment by bobbyrauchenberg** [comment]
Updated as requested

**Comment by tdietert** [comment]
This looks good! I hope you don't mind me waiting until Saturday to merge-- I am planning to put in a few hours this weekend. Thanks!

**Comment by bobbyrauchenberg** [comment]
Sounds good!

**Comment by tdietert** [comment]
Closing in favor of #24

**Pull request closed without merging**
